// { ru, en, label, enLabel, timezone }
const CITIES = [
  // Россия
  { ru: 'Москва',                    en: 'Moscow',              label: 'МСК', enLabel: 'MSK', timezone: 'Europe/Moscow' },
  { ru: 'Санкт-Петербург',           en: 'Saint Petersburg',    label: 'СПБ', enLabel: 'SPB', timezone: 'Europe/Moscow' },
  { ru: 'Калининград',               en: 'Kaliningrad',         label: 'КЛН', enLabel: 'KLD', timezone: 'Europe/Kaliningrad' },
  { ru: 'Самара',                    en: 'Samara',              label: 'СМР', enLabel: 'SAM', timezone: 'Europe/Samara' },
  { ru: 'Уфа',                       en: 'Ufa',                 label: 'УФА', enLabel: 'UFA', timezone: 'Asia/Yekaterinburg' },
  { ru: 'Екатеринбург',              en: 'Yekaterinburg',       label: 'ЕКБ', enLabel: 'EKB', timezone: 'Asia/Yekaterinburg' },
  { ru: 'Челябинск',                 en: 'Chelyabinsk',         label: 'ЧЛБ', enLabel: 'CHE', timezone: 'Asia/Yekaterinburg' },
  { ru: 'Омск',                      en: 'Omsk',                label: 'ОМС', enLabel: 'OMS', timezone: 'Asia/Omsk' },
  { ru: 'Новосибирск',               en: 'Novosibirsk',         label: 'НСК', enLabel: 'NVS', timezone: 'Asia/Novosibirsk' },
  { ru: 'Кемерово',                  en: 'Kemerovo',            label: 'КЕМ', enLabel: 'KEM', timezone: 'Asia/Novosibirsk' },
  { ru: 'Томск',                     en: 'Tomsk',               label: 'ТМС', enLabel: 'TMS', timezone: 'Asia/Tomsk' },
  { ru: 'Барнаул',                   en: 'Barnaul',             label: 'БАР', enLabel: 'BAR', timezone: 'Asia/Barnaul' },
  { ru: 'Красноярск',                en: 'Krasnoyarsk',         label: 'КРС', enLabel: 'KRS', timezone: 'Asia/Krasnoyarsk' },
  { ru: 'Иркутск',                   en: 'Irkutsk',             label: 'ИРК', enLabel: 'IKT', timezone: 'Asia/Irkutsk' },
  { ru: 'Чита',                      en: 'Chita',               label: 'ЧИТ', enLabel: 'CHT', timezone: 'Asia/Chita' },
  { ru: 'Якутск',                    en: 'Yakutsk',             label: 'ЯКТ', enLabel: 'YKT', timezone: 'Asia/Yakutsk' },
  { ru: 'Благовещенск',              en: 'Blagoveshchensk',     label: 'БЛГ', enLabel: 'BLG', timezone: 'Asia/Yakutsk' },
  { ru: 'Хабаровск',                 en: 'Khabarovsk',          label: 'ХБР', enLabel: 'KHV', timezone: 'Asia/Vladivostok' },
  { ru: 'Владивосток',               en: 'Vladivostok',         label: 'ВЛД', enLabel: 'VVO', timezone: 'Asia/Vladivostok' },
  { ru: 'Магадан',                   en: 'Magadan',             label: 'МГД', enLabel: 'MGD', timezone: 'Asia/Magadan' },
  { ru: 'Южно-Сахалинск',            en: 'Yuzhno-Sakhalinsk',   label: 'ЮСХ', enLabel: 'UUS', timezone: 'Asia/Sakhalin' },
  { ru: 'Петропавловск-Камчатский',  en: 'Petropavlovsk',       label: 'ПКМ', enLabel: 'PKC', timezone: 'Asia/Kamchatka' },
  // СНГ
  { ru: 'Минск',                     en: 'Minsk',               label: 'МНС', enLabel: 'MSQ', timezone: 'Europe/Minsk' },
  { ru: 'Киев',                      en: 'Kyiv',                label: 'КИВ', enLabel: 'KIV', timezone: 'Europe/Kiev' },
  { ru: 'Алматы',                    en: 'Almaty',              label: 'АЛМ', enLabel: 'ALA', timezone: 'Asia/Almaty' },
  { ru: 'Астана',                    en: 'Astana',              label: 'АСТ', enLabel: 'TSE', timezone: 'Asia/Almaty' },
  { ru: 'Ташкент',                   en: 'Tashkent',            label: 'ТШК', enLabel: 'TAS', timezone: 'Asia/Tashkent' },
  { ru: 'Бишкек',                    en: 'Bishkek',             label: 'БШК', enLabel: 'FRU', timezone: 'Asia/Bishkek' },
  { ru: 'Душанбе',                   en: 'Dushanbe',            label: 'ДШБ', enLabel: 'DYU', timezone: 'Asia/Dushanbe' },
  { ru: 'Ашхабад',                   en: 'Ashgabat',            label: 'АШГ', enLabel: 'ASB', timezone: 'Asia/Ashgabat' },
  { ru: 'Баку',                      en: 'Baku',                label: 'БКУ', enLabel: 'BAK', timezone: 'Asia/Baku' },
  { ru: 'Ереван',                    en: 'Yerevan',             label: 'ЕРВ', enLabel: 'EVN', timezone: 'Asia/Yerevan' },
  { ru: 'Тбилиси',                   en: 'Tbilisi',             label: 'ТБЛ', enLabel: 'TBS', timezone: 'Asia/Tbilisi' },
  // Европа
  { ru: 'Лондон',                    en: 'London',              label: 'ЛОН', enLabel: 'LON', timezone: 'Europe/London' },
  { ru: 'Дублин',                    en: 'Dublin',              label: 'ДБЛ', enLabel: 'DUB', timezone: 'Europe/Dublin' },
  { ru: 'Лиссабон',                  en: 'Lisbon',              label: 'ЛСБ', enLabel: 'LIS', timezone: 'Europe/Lisbon' },
  { ru: 'Мадрид',                    en: 'Madrid',              label: 'МАД', enLabel: 'MAD', timezone: 'Europe/Madrid' },
  { ru: 'Париж',                     en: 'Paris',               label: 'ПАР', enLabel: 'PAR', timezone: 'Europe/Paris' },
  { ru: 'Берлин',                    en: 'Berlin',              label: 'БЕР', enLabel: 'BER', timezone: 'Europe/Berlin' },
  { ru: 'Амстердам',                 en: 'Amsterdam',           label: 'АМС', enLabel: 'AMS', timezone: 'Europe/Amsterdam' },
  { ru: 'Брюссель',                  en: 'Brussels',            label: 'БРЮ', enLabel: 'BRU', timezone: 'Europe/Brussels' },
  { ru: 'Цюрих',                     en: 'Zurich',              label: 'ЦЮР', enLabel: 'ZRH', timezone: 'Europe/Zurich' },
  { ru: 'Вена',                      en: 'Vienna',              label: 'ВЕН', enLabel: 'VIE', timezone: 'Europe/Vienna' },
  { ru: 'Рим',                       en: 'Rome',                label: 'РИМ', enLabel: 'ROM', timezone: 'Europe/Rome' },
  { ru: 'Прага',                     en: 'Prague',              label: 'ПРГ', enLabel: 'PRG', timezone: 'Europe/Prague' },
  { ru: 'Варшава',                   en: 'Warsaw',              label: 'ВАР', enLabel: 'WAW', timezone: 'Europe/Warsaw' },
  { ru: 'Будапешт',                  en: 'Budapest',            label: 'БДП', enLabel: 'BUD', timezone: 'Europe/Budapest' },
  { ru: 'Бухарест',                  en: 'Bucharest',           label: 'БХР', enLabel: 'OTP', timezone: 'Europe/Bucharest' },
  { ru: 'Афины',                     en: 'Athens',              label: 'АФН', enLabel: 'ATH', timezone: 'Europe/Athens' },
  { ru: 'Стамбул',                   en: 'Istanbul',            label: 'СТМ', enLabel: 'IST', timezone: 'Europe/Istanbul' },
  { ru: 'Стокгольм',                 en: 'Stockholm',           label: 'СТК', enLabel: 'STO', timezone: 'Europe/Stockholm' },
  { ru: 'Осло',                      en: 'Oslo',                label: 'ОСЛ', enLabel: 'OSL', timezone: 'Europe/Oslo' },
  { ru: 'Копенгаген',                en: 'Copenhagen',          label: 'КПГ', enLabel: 'CPH', timezone: 'Europe/Copenhagen' },
  { ru: 'Хельсинки',                 en: 'Helsinki',            label: 'ХЕЛ', enLabel: 'HEL', timezone: 'Europe/Helsinki' },
  { ru: 'Рига',                      en: 'Riga',                label: 'РИГ', enLabel: 'RIX', timezone: 'Europe/Riga' },
  { ru: 'Таллин',                    en: 'Tallinn',             label: 'ТЛН', enLabel: 'TLL', timezone: 'Europe/Tallinn' },
  { ru: 'Вильнюс',                   en: 'Vilnius',             label: 'ВЛН', enLabel: 'VNO', timezone: 'Europe/Vilnius' },
  // Ближний Восток
  { ru: 'Дубай',                     en: 'Dubai',               label: 'ДБ',  enLabel: 'DXB', timezone: 'Asia/Dubai' },
  { ru: 'Абу-Даби',                  en: 'Abu Dhabi',           label: 'АБД', enLabel: 'AUH', timezone: 'Asia/Dubai' },
  { ru: 'Доха',                      en: 'Doha',                label: 'ДОХ', enLabel: 'DOH', timezone: 'Asia/Qatar' },
  { ru: 'Эр-Рияд',                   en: 'Riyadh',              label: 'РЯД', enLabel: 'RUH', timezone: 'Asia/Riyadh' },
  { ru: 'Тель-Авив',                 en: 'Tel Aviv',            label: 'ТЛВ', enLabel: 'TLV', timezone: 'Asia/Jerusalem' },
  { ru: 'Бейрут',                    en: 'Beirut',              label: 'БЕЙ', enLabel: 'BEY', timezone: 'Asia/Beirut' },
  { ru: 'Тегеран',                   en: 'Tehran',              label: 'ТЕГ', enLabel: 'THR', timezone: 'Asia/Tehran' },
  { ru: 'Багдад',                    en: 'Baghdad',             label: 'БГД', enLabel: 'BGW', timezone: 'Asia/Baghdad' },
  { ru: 'Кувейт',                    en: 'Kuwait',              label: 'КВТ', enLabel: 'KWI', timezone: 'Asia/Kuwait' },
  // Азия
  { ru: 'Карачи',                    en: 'Karachi',             label: 'КРЧ', enLabel: 'KHI', timezone: 'Asia/Karachi' },
  { ru: 'Дели',                      en: 'Delhi',               label: 'ДЕЛ', enLabel: 'DEL', timezone: 'Asia/Kolkata' },
  { ru: 'Мумбаи',                    en: 'Mumbai',              label: 'МУМ', enLabel: 'BOM', timezone: 'Asia/Kolkata' },
  { ru: 'Колката',                   en: 'Kolkata',             label: 'КЛК', enLabel: 'CCU', timezone: 'Asia/Kolkata' },
  { ru: 'Бангалор',                  en: 'Bangalore',           label: 'БНГ', enLabel: 'BLR', timezone: 'Asia/Kolkata' },
  { ru: 'Катманду',                  en: 'Kathmandu',           label: 'КТМ', enLabel: 'KTM', timezone: 'Asia/Kathmandu' },
  { ru: 'Дакка',                     en: 'Dhaka',               label: 'ДАК', enLabel: 'DAC', timezone: 'Asia/Dhaka' },
  { ru: 'Коломбо',                   en: 'Colombo',             label: 'КЛМ', enLabel: 'CMB', timezone: 'Asia/Colombo' },
  { ru: 'Янгон',                     en: 'Yangon',              label: 'ЯНГ', enLabel: 'RGN', timezone: 'Asia/Rangoon' },
  { ru: 'Бангкок',                   en: 'Bangkok',             label: 'БНК', enLabel: 'BKK', timezone: 'Asia/Bangkok' },
  { ru: 'Джакарта',                  en: 'Jakarta',             label: 'ДЖК', enLabel: 'JKT', timezone: 'Asia/Jakarta' },
  { ru: 'Куала-Лумпур',              en: 'Kuala Lumpur',        label: 'КЛМ', enLabel: 'KUL', timezone: 'Asia/Kuala_Lumpur' },
  { ru: 'Сингапур',                  en: 'Singapore',           label: 'СНГ', enLabel: 'SIN', timezone: 'Asia/Singapore' },
  { ru: 'Манила',                    en: 'Manila',              label: 'МНЛ', enLabel: 'MNL', timezone: 'Asia/Manila' },
  { ru: 'Гонконг',                   en: 'Hong Kong',           label: 'ГКГ', enLabel: 'HKG', timezone: 'Asia/Hong_Kong' },
  { ru: 'Шанхай',                    en: 'Shanghai',            label: 'ШНГ', enLabel: 'SHA', timezone: 'Asia/Shanghai' },
  { ru: 'Пекин',                     en: 'Beijing',             label: 'ПЕК', enLabel: 'PEK', timezone: 'Asia/Shanghai' },
  { ru: 'Сеул',                      en: 'Seoul',               label: 'СЕУ', enLabel: 'SEL', timezone: 'Asia/Seoul' },
  { ru: 'Токио',                     en: 'Tokyo',               label: 'ТОК', enLabel: 'TYO', timezone: 'Asia/Tokyo' },
  { ru: 'Осака',                     en: 'Osaka',               label: 'ОСК', enLabel: 'OSA', timezone: 'Asia/Tokyo' },
  { ru: 'Тайбэй',                    en: 'Taipei',              label: 'ТБЙ', enLabel: 'TPE', timezone: 'Asia/Taipei' },
  { ru: 'Улан-Батор',                en: 'Ulaanbaatar',         label: 'УБТ', enLabel: 'ULN', timezone: 'Asia/Ulaanbaatar' },
  // Африка
  { ru: 'Каир',                      en: 'Cairo',               label: 'КАИ', enLabel: 'CAI', timezone: 'Africa/Cairo' },
  { ru: 'Касабланка',                en: 'Casablanca',          label: 'КАС', enLabel: 'CAS', timezone: 'Africa/Casablanca' },
  { ru: 'Лагос',                     en: 'Lagos',               label: 'ЛАГ', enLabel: 'LOS', timezone: 'Africa/Lagos' },
  { ru: 'Найроби',                   en: 'Nairobi',             label: 'НАЙ', enLabel: 'NBO', timezone: 'Africa/Nairobi' },
  { ru: 'Йоханнесбург',              en: 'Johannesburg',        label: 'ЙХН', enLabel: 'JNB', timezone: 'Africa/Johannesburg' },
  { ru: 'Аддис-Абеба',               en: 'Addis Ababa',         label: 'ААБ', enLabel: 'ADD', timezone: 'Africa/Addis_Ababa' },
  // Северная Америка
  { ru: 'Нью-Йорк',                  en: 'New York',            label: 'НЙ',  enLabel: 'NYC', timezone: 'America/New_York' },
  { ru: 'Вашингтон',                 en: 'Washington',          label: 'ВШН', enLabel: 'DCA', timezone: 'America/New_York' },
  { ru: 'Бостон',                    en: 'Boston',              label: 'БСТ', enLabel: 'BOS', timezone: 'America/New_York' },
  { ru: 'Майами',                    en: 'Miami',               label: 'МАЙ', enLabel: 'MIA', timezone: 'America/New_York' },
  { ru: 'Торонто',                   en: 'Toronto',             label: 'ТОР', enLabel: 'YTO', timezone: 'America/Toronto' },
  { ru: 'Чикаго',                    en: 'Chicago',             label: 'ЧИК', enLabel: 'CHI', timezone: 'America/Chicago' },
  { ru: 'Даллас',                    en: 'Dallas',              label: 'ДАЛ', enLabel: 'DAL', timezone: 'America/Chicago' },
  { ru: 'Денвер',                    en: 'Denver',              label: 'ДЕН', enLabel: 'DEN', timezone: 'America/Denver' },
  { ru: 'Лос-Анджелес',              en: 'Los Angeles',         label: 'ЛА',  enLabel: 'LAX', timezone: 'America/Los_Angeles' },
  { ru: 'Сан-Франциско',             en: 'San Francisco',       label: 'СФ',  enLabel: 'SFO', timezone: 'America/Los_Angeles' },
  { ru: 'Сиэтл',                     en: 'Seattle',             label: 'СИТ', enLabel: 'SEA', timezone: 'America/Los_Angeles' },
  { ru: 'Ванкувер',                  en: 'Vancouver',           label: 'ВНК', enLabel: 'YVR', timezone: 'America/Vancouver' },
  { ru: 'Мехико',                    en: 'Mexico City',         label: 'МХК', enLabel: 'MEX', timezone: 'America/Mexico_City' },
  { ru: 'Гавана',                    en: 'Havana',              label: 'ГВН', enLabel: 'HAV', timezone: 'America/Havana' },
  { ru: 'Монреаль',                  en: 'Montreal',            label: 'МТР', enLabel: 'YMQ', timezone: 'America/Toronto' },
  { ru: 'Анкоридж',                  en: 'Anchorage',           label: 'АНК', enLabel: 'ANC', timezone: 'America/Anchorage' },
  { ru: 'Гонолулу',                  en: 'Honolulu',            label: 'ГНЛ', enLabel: 'HNL', timezone: 'Pacific/Honolulu' },
  // Южная Америка
  { ru: 'Богота',                    en: 'Bogota',              label: 'БГТ', enLabel: 'BOG', timezone: 'America/Bogota' },
  { ru: 'Лима',                      en: 'Lima',                label: 'ЛИМ', enLabel: 'LIM', timezone: 'America/Lima' },
  { ru: 'Сантьяго',                  en: 'Santiago',            label: 'СТЯ', enLabel: 'SCL', timezone: 'America/Santiago' },
  { ru: 'Буэнос-Айрес',              en: 'Buenos Aires',        label: 'БАС', enLabel: 'BUE', timezone: 'America/Argentina/Buenos_Aires' },
  { ru: 'Сан-Паулу',                 en: 'Sao Paulo',           label: 'СПЛ', enLabel: 'SAO', timezone: 'America/Sao_Paulo' },
  { ru: 'Рио-де-Жанейро',            en: 'Rio de Janeiro',      label: 'РИО', enLabel: 'RIO', timezone: 'America/Sao_Paulo' },
  // Австралия и Океания
  { ru: 'Перт',                      en: 'Perth',               label: 'ПРТ', enLabel: 'PER', timezone: 'Australia/Perth' },
  { ru: 'Аделаида',                  en: 'Adelaide',            label: 'АДЛ', enLabel: 'ADL', timezone: 'Australia/Adelaide' },
  { ru: 'Сидней',                    en: 'Sydney',              label: 'СИД', enLabel: 'SYD', timezone: 'Australia/Sydney' },
  { ru: 'Мельбурн',                  en: 'Melbourne',           label: 'МЛБ', enLabel: 'MEL', timezone: 'Australia/Melbourne' },
  { ru: 'Брисбен',                   en: 'Brisbane',            label: 'БРС', enLabel: 'BNE', timezone: 'Australia/Brisbane' },
  { ru: 'Окленд',                    en: 'Auckland',            label: 'ОКЛ', enLabel: 'AKL', timezone: 'Pacific/Auckland' },
]

module.exports = CITIES
